package com.example.hisabapp.ui

import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import com.example.hisabapp.databinding.ActivityAddTransactionBinding
import com.example.hisabapp.data.model.Transaction
import com.example.hisabapp.viewmodel.TransactionViewModel
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class AddTransactionActivity : AppCompatActivity() {

    private lateinit var binding: ActivityAddTransactionBinding
    private val viewModel: TransactionViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityAddTransactionBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setupCategorySpinner()
        setupClickListeners()
    }

    private fun setupCategorySpinner() {
        val categories = arrayOf(
            "Food & Dining",
            "Transportation",
            "Shopping",
            "Entertainment",
            "Bills & Utilities",
            "Health & Fitness",
            "Education",
            "Other"
        )

        val adapter = ArrayAdapter(
            this,
            android.R.layout.simple_spinner_dropdown_item,
            categories
        )
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        binding.categorySpinner.adapter = adapter
    }

    private fun setupClickListeners() {
        binding.saveButton.setOnClickListener {
            saveTransaction()
        }
    }

    private fun saveTransaction() {
        val name = binding.nameInput.text.toString().trim()
        val mobile = binding.mobileNumberInput.text.toString().trim()
        val amount = binding.amountInput.text.toString().trim()
        val category = binding.categorySpinner.selectedItem.toString()
        val description = binding.descriptionInput.text.toString().trim()
        val isIncome = binding.incomeRadio.isChecked

        // Basic validation
        if (name.isEmpty()) {
            binding.nameInput.error = "Name is required"
            return
        }

        if (amount.isEmpty()) {
            binding.amountInput.error = "Amount is required"
            return
        }

        try {
            val amountValue = amount.toDouble()
            val type = if (isIncome) "Income" else "Expense"
            val date = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())

            val transaction = Transaction(
                amount = amountValue,
                category = category,
                date = date,
                type = type,
                description = description,
                id = 0, // Will be auto-generated by Room
                name = name,
                mobileNumber = mobile
            )

            viewModel.insert(transaction)
            Toast.makeText(this, "Transaction saved successfully!", Toast.LENGTH_SHORT).show()
            finish()
        } catch (e: NumberFormatException) {
            binding.amountInput.error = "Please enter a valid amount"
        }
    }
}